/* 
 * PizzaBox.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IValuesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <param name="CRUST"></param>
        /// <param name="TOPPING"> (optional)</param>
        /// <returns>APizza</returns>
        APizza ApiValuesPIZZASIZECRUSTGet (PIZZAS PIZZA, SIZES SIZE, CRUSTS CRUST, List<TOPPINGS> TOPPING = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <param name="CRUST"></param>
        /// <param name="TOPPING"> (optional)</param>
        /// <returns>ApiResponse of APizza</returns>
        ApiResponse<APizza> ApiValuesPIZZASIZECRUSTGetWithHttpInfo (PIZZAS PIZZA, SIZES SIZE, CRUSTS CRUST, List<TOPPINGS> TOPPING = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <returns>APizza</returns>
        APizza ApiValuesPIZZASIZEGet (PIZZAS PIZZA, SIZES SIZE);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <returns>ApiResponse of APizza</returns>
        ApiResponse<APizza> ApiValuesPIZZASIZEGetWithHttpInfo (PIZZAS PIZZA, SIZES SIZE);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <param name="CRUST"></param>
        /// <param name="TOPPING"> (optional)</param>
        /// <returns>Task of APizza</returns>
        System.Threading.Tasks.Task<APizza> ApiValuesPIZZASIZECRUSTGetAsync (PIZZAS PIZZA, SIZES SIZE, CRUSTS CRUST, List<TOPPINGS> TOPPING = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <param name="CRUST"></param>
        /// <param name="TOPPING"> (optional)</param>
        /// <returns>Task of ApiResponse (APizza)</returns>
        System.Threading.Tasks.Task<ApiResponse<APizza>> ApiValuesPIZZASIZECRUSTGetAsyncWithHttpInfo (PIZZAS PIZZA, SIZES SIZE, CRUSTS CRUST, List<TOPPINGS> TOPPING = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <returns>Task of APizza</returns>
        System.Threading.Tasks.Task<APizza> ApiValuesPIZZASIZEGetAsync (PIZZAS PIZZA, SIZES SIZE);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <returns>Task of ApiResponse (APizza)</returns>
        System.Threading.Tasks.Task<ApiResponse<APizza>> ApiValuesPIZZASIZEGetAsyncWithHttpInfo (PIZZAS PIZZA, SIZES SIZE);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class ValuesApi : IValuesApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ValuesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ValuesApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValuesApi"/> class
        /// </summary>
        /// <returns></returns>
        public ValuesApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValuesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ValuesApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <param name="CRUST"></param>
        /// <param name="TOPPING"> (optional)</param>
        /// <returns>APizza</returns>
        public APizza ApiValuesPIZZASIZECRUSTGet (PIZZAS PIZZA, SIZES SIZE, CRUSTS CRUST, List<TOPPINGS> TOPPING = null)
        {
             ApiResponse<APizza> localVarResponse = ApiValuesPIZZASIZECRUSTGetWithHttpInfo(PIZZA, SIZE, CRUST, TOPPING);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <param name="CRUST"></param>
        /// <param name="TOPPING"> (optional)</param>
        /// <returns>ApiResponse of APizza</returns>
        public ApiResponse< APizza > ApiValuesPIZZASIZECRUSTGetWithHttpInfo (PIZZAS PIZZA, SIZES SIZE, CRUSTS CRUST, List<TOPPINGS> TOPPING = null)
        {
            // verify the required parameter 'PIZZA' is set
            if (PIZZA == null)
                throw new ApiException(400, "Missing required parameter 'PIZZA' when calling ValuesApi->ApiValuesPIZZASIZECRUSTGet");
            // verify the required parameter 'SIZE' is set
            if (SIZE == null)
                throw new ApiException(400, "Missing required parameter 'SIZE' when calling ValuesApi->ApiValuesPIZZASIZECRUSTGet");
            // verify the required parameter 'CRUST' is set
            if (CRUST == null)
                throw new ApiException(400, "Missing required parameter 'CRUST' when calling ValuesApi->ApiValuesPIZZASIZECRUSTGet");

            var localVarPath = "/api/Values/{PIZZA}/{SIZE}/{CRUST}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (PIZZA != null) localVarPathParams.Add("PIZZA", this.Configuration.ApiClient.ParameterToString(PIZZA)); // path parameter
            if (SIZE != null) localVarPathParams.Add("SIZE", this.Configuration.ApiClient.ParameterToString(SIZE)); // path parameter
            if (CRUST != null) localVarPathParams.Add("CRUST", this.Configuration.ApiClient.ParameterToString(CRUST)); // path parameter
            if (TOPPING != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "TOPPING", TOPPING)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiValuesPIZZASIZECRUSTGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<APizza>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (APizza) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(APizza)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <param name="CRUST"></param>
        /// <param name="TOPPING"> (optional)</param>
        /// <returns>Task of APizza</returns>
        public async System.Threading.Tasks.Task<APizza> ApiValuesPIZZASIZECRUSTGetAsync (PIZZAS PIZZA, SIZES SIZE, CRUSTS CRUST, List<TOPPINGS> TOPPING = null)
        {
             ApiResponse<APizza> localVarResponse = await ApiValuesPIZZASIZECRUSTGetAsyncWithHttpInfo(PIZZA, SIZE, CRUST, TOPPING);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <param name="CRUST"></param>
        /// <param name="TOPPING"> (optional)</param>
        /// <returns>Task of ApiResponse (APizza)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<APizza>> ApiValuesPIZZASIZECRUSTGetAsyncWithHttpInfo (PIZZAS PIZZA, SIZES SIZE, CRUSTS CRUST, List<TOPPINGS> TOPPING = null)
        {
            // verify the required parameter 'PIZZA' is set
            if (PIZZA == null)
                throw new ApiException(400, "Missing required parameter 'PIZZA' when calling ValuesApi->ApiValuesPIZZASIZECRUSTGet");
            // verify the required parameter 'SIZE' is set
            if (SIZE == null)
                throw new ApiException(400, "Missing required parameter 'SIZE' when calling ValuesApi->ApiValuesPIZZASIZECRUSTGet");
            // verify the required parameter 'CRUST' is set
            if (CRUST == null)
                throw new ApiException(400, "Missing required parameter 'CRUST' when calling ValuesApi->ApiValuesPIZZASIZECRUSTGet");

            var localVarPath = "/api/Values/{PIZZA}/{SIZE}/{CRUST}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (PIZZA != null) localVarPathParams.Add("PIZZA", this.Configuration.ApiClient.ParameterToString(PIZZA)); // path parameter
            if (SIZE != null) localVarPathParams.Add("SIZE", this.Configuration.ApiClient.ParameterToString(SIZE)); // path parameter
            if (CRUST != null) localVarPathParams.Add("CRUST", this.Configuration.ApiClient.ParameterToString(CRUST)); // path parameter
            if (TOPPING != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "TOPPING", TOPPING)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiValuesPIZZASIZECRUSTGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<APizza>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (APizza) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(APizza)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <returns>APizza</returns>
        public APizza ApiValuesPIZZASIZEGet (PIZZAS PIZZA, SIZES SIZE)
        {
             ApiResponse<APizza> localVarResponse = ApiValuesPIZZASIZEGetWithHttpInfo(PIZZA, SIZE);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <returns>ApiResponse of APizza</returns>
        public ApiResponse< APizza > ApiValuesPIZZASIZEGetWithHttpInfo (PIZZAS PIZZA, SIZES SIZE)
        {
            // verify the required parameter 'PIZZA' is set
            if (PIZZA == null)
                throw new ApiException(400, "Missing required parameter 'PIZZA' when calling ValuesApi->ApiValuesPIZZASIZEGet");
            // verify the required parameter 'SIZE' is set
            if (SIZE == null)
                throw new ApiException(400, "Missing required parameter 'SIZE' when calling ValuesApi->ApiValuesPIZZASIZEGet");

            var localVarPath = "/api/Values/{PIZZA}/{SIZE}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (PIZZA != null) localVarPathParams.Add("PIZZA", this.Configuration.ApiClient.ParameterToString(PIZZA)); // path parameter
            if (SIZE != null) localVarPathParams.Add("SIZE", this.Configuration.ApiClient.ParameterToString(SIZE)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiValuesPIZZASIZEGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<APizza>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (APizza) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(APizza)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <returns>Task of APizza</returns>
        public async System.Threading.Tasks.Task<APizza> ApiValuesPIZZASIZEGetAsync (PIZZAS PIZZA, SIZES SIZE)
        {
             ApiResponse<APizza> localVarResponse = await ApiValuesPIZZASIZEGetAsyncWithHttpInfo(PIZZA, SIZE);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="PIZZA"></param>
        /// <param name="SIZE"></param>
        /// <returns>Task of ApiResponse (APizza)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<APizza>> ApiValuesPIZZASIZEGetAsyncWithHttpInfo (PIZZAS PIZZA, SIZES SIZE)
        {
            // verify the required parameter 'PIZZA' is set
            if (PIZZA == null)
                throw new ApiException(400, "Missing required parameter 'PIZZA' when calling ValuesApi->ApiValuesPIZZASIZEGet");
            // verify the required parameter 'SIZE' is set
            if (SIZE == null)
                throw new ApiException(400, "Missing required parameter 'SIZE' when calling ValuesApi->ApiValuesPIZZASIZEGet");

            var localVarPath = "/api/Values/{PIZZA}/{SIZE}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (PIZZA != null) localVarPathParams.Add("PIZZA", this.Configuration.ApiClient.ParameterToString(PIZZA)); // path parameter
            if (SIZE != null) localVarPathParams.Add("SIZE", this.Configuration.ApiClient.ParameterToString(SIZE)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiValuesPIZZASIZEGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<APizza>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (APizza) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(APizza)));
        }

    }
}
